### ISSUE TITLE
Add a "reason code"

### ISSUE THREAD

**Issue by lrosenthol** [w3c/vc-bitstring-status-list#12]
CRL's support an optional `reasonCode` field (https://datatracker.ietf.org/doc/html/rfc5280#section-5.3.1) that enables the CA to specify the reason for revocation, so that the validator can determine the severity of the revocation and chose different handling.  Having an equivalent here would be extremely helpful.

**Comment by lemoustachiste** [comment]
I think it could be useful.
Maybe a naive approach would be to have a second string (optional) the same size as the bit string (so the index is lookable and matches the status index), and the value could go from 0 to 9. 

Does someone know why CRL does not make use of `7` but uses `10` instead? I am not sure the codes have to follow CRL's though.

**Comment by sbutterfield** [comment]
+1

**Comment by OR13** [comment]
discussed on the call, seems fraught with privacy issues, suggest not implementing it.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-24-vcwg-special#section1-6) on 2023-01-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.6. Add a "reason code" (issue vc-status-list-2021#12)

_See github issue [vc-status-list-2021#12](https://github.com/w3c/vc-status-list-2021/issues/12)._




**Kristina Yasuda:** issue 12.  
… Adding reason field. Which sounds useful..  

**Manu Sporny:** I agree it would be useful.  
… but I'm concerned about size.  
… The whole point is of Status List is to scale well.  
… Also, it leaks privacy.  
… And is the reason just an open text?.  
… The issuer should keep track of why, and they should be able to explain why to the appropriate parties.  
… That's between the individual and the issuer, not information that is publicized.  
… Presently, I'd be -1 to this.  
… Because the use case isn't clear.  
… and we don't have enough experience to say what all the codes would be.  

**Dave Longley:** Agree with manu. This seems like something that is very hard to do while preserving the privacy of the holder..  
… solving this in a general way that won't be abused is fraught.  

**Gregory Natran:** echoing Manu. At least in Canada, you could run into real problems with privacy law..  
… it may not be your concern that its suspended for repeat DUI verses something less serious.  

**Kristina Yasuda:** let's document that there's no consensus on adopting this feature and we can revisit later.  
… with two minutes left.  

</details>

**Comment by msporny** [comment]
This can now be handled with the multi-bit value for a status list that supports that. That said, the privacy concerns remain. So much so that having two different types of status lists might be needed from a privacy standpoint.

**Comment by msporny** [comment]
See this `credentialSubject.size` for a hint on how this works. I'll note that there is probably more changes that will need to occur before the data model is frozen: https://w3c.github.io/vc-status-list-2021/#bitstringstatuslistcredential

**Comment by msporny** [comment]
Closing this issue as there is a mechanism to do this in the specification today.
