### ISSUE TITLE
Matching of VC issuer and Status List VC issuer - MAY vs MUST

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/vc-bitstring-status-list#124]
In implementing this, we've noticed that some of the status list libraries require that the issuer of a revocable VC MUST match the issuer of the revocation status list VC it links to! (and throw errors if that's not the case).

It would be great if we could clarify this explicitly in the spec.

We'd like to also make an argument for why it should be a MAY but not MUST. As @jchartrand pointed out:

> The decoupling [of the VC's issuer and the status list's issuer] seems pretty important.  I could think of at least three scenarios where you'd want a different signing key on the Status List VC than on the credential VCs:
> 1. For whatever reason - legal, politically, institutional - you may not want the issuer to control revocation. Revocation might be done by someone else, maybe because a revocation first has to be reviewed and approved by someone else.  A university degree might be an example.  The registrar issues it, but revocation might be handled - because it is so sensitive - by the university senate.
> 2. There are many issuers within a university (economics, engineering, etc.) each with their own issuing key, but all of whom share the same Status List.
> 3. You may want to rotate the signing keys for credentials, but not for the status list.

**Comment by msporny** [comment]
We need to make sure that the specification does not require the issuer of the original VC to have to match the issuer of the status list VC. It's probably going to be the case in many situations, but there may be use cases where the original issuer of the VC is not the one that continues to maintain its validity.

**Comment by msporny** [comment]
PR #129 has been raised to address this issue. This issue will be closed once PR #129 has been merged.

**Comment by dmitrizagidulin** [comment]
(Can confirm - PR #129 addresses this issue.)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-16-vcwg-special#section2-3) on 2024-01-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Matching of VC issuer and Status List VC issuer - MAY vs MUST (issue vc-bitstring-status-list#124)

_See github issue [vc-bitstring-status-list#124](https://github.com/w3c/vc-bitstring-status-list/issues/124)._




**Manu Sporny:** This was a request from dmitriz. They requested clarification from the spec, which is what PR 129 does. As a result, merging will address 124. TallTed has some minor fixups in the PR.  

</details>

**Comment by msporny** [comment]
PR #129 has been merged, closing.
