### ISSUE TITLE
Add `@type` to `encodedList` term definition

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-bitstring-status-list#125]
We should include a type for the term definition. Notably, it's a base64url-no-pad encoded field and I'm not aware of any existing vocabularies we could leverage for that type. It may be better to follow what we've done elsewhere and make it a multibase field.

Including a multibase type for the field would enable compression which could be very useful for large status lists.

**Comment by msporny** [comment]
I can mention that the field is multibase encoded where the encoding MUST be base64url-no-pad encoded and start with a `u` character.

**Comment by msporny** [comment]
PR #130 has been raised to address this issue. This issue will be closed once PR #130 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-16-vcwg-special#section2-5) on 2024-01-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. Add `@type` to `encodedList` term definition (issue vc-bitstring-status-list#125)

_See github issue [vc-bitstring-status-list#125](https://github.com/w3c/vc-bitstring-status-list/issues/125)._




**Brent Zundel:** Has PRs, expected to be merged soon.  

**Manu Sporny:** Want to highlight that we want to make possible for systems to compress this data.  
… Status list might be hundreds of KB, plus bloat of encoding.  
… This allows reduction by defining a type. This group defined multibase with a u prefix on it.  
… We changed this from base64 with padding to base64 nopad.  

</details>

**Comment by msporny** [comment]
PR #130 has been merged, closing.
