### ISSUE TITLE
Can the spec relax/remove the requirement on minimal bit length?

### ISSUE THREAD

**Issue by thehenrytsai** [w3c/vc-bitstring-status-list#14]
We find the minimum bit length requirement of 131,072 (16 KiB) in the [spec](https://w3c-ccg.github.io/vc-status-list-2021/#statuslist2021credential) is quite arbitrary and limiting, can we make this requirement non-normative instead?

It is clear that the shorter the length the lesser the herd-privacy protection, but there is a case to be made that it is up to the use case and creator to decide the length.

**Comment by jandrieu** [comment]
@thehenrytsai What's the use case you are trying to address? Although the 16KB limit is arbitrary, it provides a quantifiable floor for herd privacy. 

The sense of the group is that far too many developers will just do the minimum or choose the default, so to empower users across the board, we need a floor to assure that the quick-to-market developer ships something reasonable.

It was claimed that compressing a 16KB bitstring typically reduces to a few hundred bytes (in scenarios with relatively few flipped bits). 

If you have a use case that needs a smaller data size, we might be able to help find alternative solutions that maintain that herd privacy characteristic.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-15-vcwg#section1-7) on 2023-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.7. Can the spec relax/remove the requirement on minimal bit length? (issue vc-status-list-2021#14)

_See github issue [vc-status-list-2021#14](https://github.com/w3c/vc-status-list-2021/issues/14)._




**Manu Sporny:** asks if we can relax / remove the requirement on the minimum bit for the status list ...  
… currently 16 KBs.  
… the concern here is around privacy .... providing at least a minimum ...  
… do we want to leave the hard privacy decision to the implementors?  
… some authors of the status list may pick minimum population sizes that do not provide hard privacy?  
… or at least we could provide a floor.  
… do we want a minimum guaranteed privacy setting for these lists?  
… or do we want ot leave that open to authors? understanding that they can pick bad values.  

> *Gabe Cohen:* +1 keep the floor.

**Joe Andrieu:** i agree that it is arbitrary.  
… but i do agree that we need a floor.  
… most people use defaults, should be a good one.  

**Manu Sporny:** the current number is arbitrary.  
… we took 16 KBs and run through gzip .... seemed reasonable ...  
… we could increase/decrease ... but very strongly arguing that we should have a decent floor.  
… since we are going to multibits ... we should try to get good defaults.  
… responding to dwait, the verifier shoud reject.  

**Kristina Yasuda:** we can't make a decision right now, need input from implementors ...  

**Joe Andrieu:** we should ask a specific use case ... maybe it is an iot situation where size matters ...  
… i'll add that comment.  

**Brent Zundel:** action is to do nothing, see if we hear back.  

</details>

**Comment by thehenrytsai** [comment]
@jandrieu, the desire at the time was to have a "nicer round" number so that it is arguably "friendlier" to end users when they read implementor's documentations and think about "orders or magnitude" of protection; it also makes it easier to have an accurate description on how the status list work when verbally describing the mechanism as opposed to giving an "approximate" number, this is something that I encountered at the time having to explain the mechanism to various people.

ie. "we aggregate 100,000 status into one list to a achieve herd-privacy..." instead of an seemingly odd arbitrary number: we aggregate 131,072 status into one list..."

But ultimately this is a nice to have IMO, not a deal breaker. Changing the default to 100,000 is also a viable alternative, a nice round number is "more meaningful" in this day of age IMO.

**Comment by msporny** [comment]
> ie. "we aggregate 100,000 status into one list to a achieve herd-privacy..." instead of an seemingly odd arbitrary number: we aggregate 131,072 status into one list..."

You can always say "We aggregate roughly 100,000 statuses into one list." <-- just change the way you convey the information to be less precise. Only developers implementing will probably care about the details; they'll be the ones that look at the specification and see the 16 KiB figure.

I'm going to close the issue without a change to the specification since this problem can be addressed by just presenting the information differently to people that don't need to understand the details. Please re-open if you disagree.
