### ISSUE TITLE
status list index is a persistent cross-origin identifier

### ISSUE THREAD

**Issue by npdoty** [w3c/vc-bitstring-status-list#142]
The status list index appears to be a cross-origin persistent identifier. The same status list index provided on a credential used on two different websites could let those websites link the user between them. This will be abused as a very effective cross-context tracking vector.

This is a serious risk for cross-context recognition. That it is persistent makes it an even greater risk to the user than other known tracking mechanisms.

For some use cases, this may not be an additional harm, if the credential being presented is itself clearly a persistent, unique cross origin identifier, like my social security number or legal name and address. But in other cases (selective disclosure presentations that might otherwise be unlinkable), this would be a serious harm. The spec needs to distinguish these and note when it is appropriate.

**Comment by msporny** [comment]
Yes, that is true; only a solution that is built on newer (potentially non-NIST approved) cryptography would be able to provide a proof of non-revocation without correlation. The WG hopes that it will be re-chartered to put that work in scope with the understanding that the use of ZKPs to provide unlinkable revocation status is still an experimental field with questionable applicability to use cases mandating NIST-approved cryptography. One of our restrictions in coming up with a solution was to use traditional cryptography that is approved by national standards setting bodies such as NIST and ETSI.

Given that traditional cryptography is required in many use cases that require a revocation list, the digital signature on a VC is a more useful correlation vector than the status list index (the signature is more generally available). As such, we expect the Bitstring Status List approach is no more correlating than using a traditional digital signature on a VC.

That is not a counter-argument to the correlatability concern raised by PING, the VCWG has the same concern; it's merely elaborating on the discussions the CCG and VCWG has had around the types of correlating information that exist in a VC (or any other modern digital credential format, such as ISO mDL).

One of the main design goals was the elimination in "phone home" to the issuer in order to prevent issuer tracking/correlation. Without the use of more advanced (and non-NIST/ETSI-approved) cryptography, we cannot eliminate the correlative effects of a status list among verifiers. There was a presentation to the CCG on this topic today; see slides 5-7 in the attached slide deck here:

https://lists.w3.org/Archives/Public/public-credentials/2024Feb/0034.html

**Comment by msporny** [comment]
To address this concern, in the privacy considerations section, the specification should distinguish where status lists are appropriate and when they would cause harm based on privacy expectations. For example, having a status list associated with a driver's license is appropriate, but having a status list (with a unique bitstring position identifier) associated with an "over 21" age verification VC would rarely be appropriate.

**Comment by msporny** [comment]
PR #160 has been raised to address this issue. This issue will be closed once PR #160 has been merged.

**Comment by msporny** [comment]
PR #160 has been merged, closing.
