### ISSUE TITLE
mitigations for risk of unique status lists

### ISSUE THREAD

**Issue by npdoty** [w3c/vc-bitstring-status-list#143]
An issuer could provide unique status list URLs per credential, in order to effectively track when a holder's credential is used at each verifier. (This threat is already noted in the privacy considerations.) The Working Group should consider mitigations for this threat, including consistency checks. 

This [draft on key consistency and discovery](https://datatracker.ietf.org/doc/draft-ietf-privacypass-key-consistency/) may be a useful starting point.

Recommendations to holders (wallet software) or to external parties that could provide accountability would both be possible.

**Comment by msporny** [comment]
Yes, the concept of ensuring that issuers are not abusing the status list to track individuals has been a topic of discussion in the group, and as you mentioned is highlighted in the privacy considerations section today:

https://www.w3.org/TR/vc-bitstring-status-list/#malicious-issuers-and-verifiers

It has been proposed that digital wallet providers track the "uniqueness" of status lists and flag status lists that seem unique to the holders that might be effected.

Seeing a message that has something to this effect might be useful: "It seems like your Electrician's license contains a tracker, when you show it to someone, Electricians Incorporated will be notified that you're showing it. Find out more by reading about how we try to protect your privacy."

That said, that is beyond the purpose of the specification -- it's way up the stack in application space. We might want to speak more directly to the concern in the privacy considerations section (perhaps in the section linked to above), because it's not obvious that we have thought about this and how to potentially mitigate the worst of it (though implementing that at scale continues to be a thought exercise).

**Comment by msporny** [comment]
While we can't put normative statements in the spec wrt. wallet software or external parties, we can write a section in the privacy considerations section with some suggestions on how wallet software could monitor the issuers to make sure they're not using the status mechanism as a tracking vector.

**Comment by msporny** [comment]
PR #160 has been raised to address this issue. This issue will be closed once PR #160 has been merged.

**Comment by msporny** [comment]
PR #161 has been merged, closing.
