### ISSUE TITLE
anonymizing proxy rather than CDN as a privacy mitigation

### ISSUE THREAD

**Issue by npdoty** [w3c/vc-bitstring-status-list#145]
CDNs are suggested as potential mitigations for hiding when a holder visited a verifier. It's not clear that CDNs provide a meaningful privacy protection; rather, anonymizing proxies could provide a more explicit design for that purpose. [Oblivious HTTP](https://datatracker.ietf.org/doc/rfc9458/) might be a better fit.

**Comment by msporny** [comment]
We do mention OHTTP here:

https://www.w3.org/TR/vc-bitstring-status-list/#malicious-issuers-and-verifiers

CDNs, while not perfect, can help ensure that traffic doesn't make it back to the issuer (and into their logs). This is of benefit to the issuer because they can't accidentally start collecting logging data on who is accessing the status list and when. They would have to specifically ask the administrators of the CDN for that information (IOW, there are policies that large organizations that do this sort of thing could put in place to ensure they're not accidentally exposing their internal IT teams to this information, which could then lead to abuse; reduce the number of potential bad actors to just the team/individual running the CDN).

We could raise a PR that moves the OHTTP language into the Algorithms section so it's easier to find. We could also try to elaborate on why a CDN, while not perfect, is better than nothing.

**Comment by npdoty** [comment]
Sorry, I misunderstood your comment before. I do see the requirement now in a different section:

**Comment by msporny** [comment]
PR #153 has been raised to address this issue. This issue will be closed once PR #153 has been merged.

**Comment by msporny** [comment]
PR #153 has been merged, closing.
