### ISSUE TITLE
comparison with alternative revocation mechanisms

### ISSUE THREAD

**Issue by npdoty** [w3c/vc-bitstring-status-list#148]
Either in the privacy considerations or elsewhere, it would be worth noting the trade-offs of this revocation mechanism relative to others.

There are alternative designs for revocation that may have different privacy properties, and might be preferable. Considering these would be a longer work item, but, for example, a stapled validity proof would be a way for a holder to prove that a credential is recently valid. Short-lived credentials could provide assurance to the verifier when necessary -- requiring the holder to more frequently interact with the issuer, but under the holder's control and without involving the particular verifier. Cryptographic accumulators could be used to efficiently communicate revocation/non-revocation status without requiring the verifier to contact the issuer.

If stapled validity proofs are possible with this mechanism, that should be described in the spec.

Some related work:
* https://datatracker.ietf.org/doc/draft-demarco-oauth-status-attestations/
* https://datatracker.ietf.org/doc/draft-steele-spice-oblivious-credential-state/

**Comment by msporny** [comment]
> There are alternative designs for revocation that may have different privacy properties, and might be preferable.

Yes, agreed, and the WG desires to be re-chartered to work on more privacy-preserving status list mechanisms. One such mechanism (ALLOSAUR) is contemplated towards the end of the slide deck linked to above.

> Considering these would be a longer work item, but, for example, a stapled validity proof would be a way for a holder to prove that a credential is recently valid.

The current specification does support "stapled validity proofs". The holder can deliver the VC and the associated status list at the same time without the verifier needing to retrieve the list from the issuer at all. We should highlight this more in the specification as it probably is not obvious that this is a possible mode of operation.

The challenge with this mode of operation is that the wallet ecosystem and the verifier ecosystem have to support it. There are use cases where one does not have the protocol bandwidth to deliver the stapled revocation list (e.g., delivering the VC over QR Code, which requires the payload to stay under 400 bytes in most use cases). The verifier could also not accept stapled revocation lists because of internal business logic that states to always fetch the revocation list from the URL provided in the VC. It is not clear if the ecosystem will support revocation list stapling, but to be clear, the specification was explicitly designed to support it (this is why the revocation lists are VCs that are signed).

> Short-lived credentials could provide assurance to the verifier when necessary -- requiring the holder to more frequently interact with the issuer, but under the holder's control and without involving the particular verifier.

Yes, the group has contemplated short-lived VCs as well and has picked that solution (instead of depending on status lists) in a variety of production deployments today. The drawback, of course, is that the holder needs frequent interaction with the issuer to refresh, and if the issuer infrastructure goes down for an extended period, then the holder loses the validity on the credential completely.

Think of national and state ID card use cases. It could be considered a privacy harm to require an individual to repeatedly get an updated national or state ID card every day, week, or month.

There are trade-offs here and perhaps the specification should highlight these trade offs a bit more in the privacy considerations section.

> Cryptographic accumulators could be used to efficiently communicate revocation/non-revocation status without requiring the verifier to contact the issuer.

We have contemplated the use of cryptographic accumulators and note that the current versions require frequent re-distribution of the proof (every time a credential is revoked in a population of N, you have to re-distribute the accumulator to the entire population of N, leading to an N^2 network load for the accumulator -- which is non-trivial amount of network traffic). There are other mechanisms that might not have this property, but I wanted to convey that we have studied and contemplated the use of accumulators and have found that there are significant drawbacks when you have large populations.

> If stapled validity proofs are possible with this mechanism, that should be described in the spec.

They are possible. We should make at least the following two changes to the specification:

1. Specify that stapled validity proofs are possible with the current mechanism.
2. Expand on how this system differs from other systems (and the trade-offs involved).

**Comment by msporny** [comment]
PR #162 has been raised to address this issue. This issue will be closed once PR #162 has been merged.

**Comment by msporny** [comment]
PR #162 has been merged, closing.

**Comment by npdoty** [comment]
Thanks for addressing these differences in the Status List spec.

Is there an update on the potential future work of more privacy-preserving revocation mechanisms that the WG is interested in taking on? Is there another issue that we can follow, or some way for Privacy folks to contribute to that topic?
