### ISSUE TITLE
The `BitstringStatusList.statusMessages` and `statusSize` properties are still being referenced

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/vc-bitstring-status-list#175]
In [Section 2.2 BitstringStatusListCredential](https://www.w3.org/TR/vc-bitstring-status-list/#bitstringstatuslistcredential) about `message` value of the `credentialSubject.statusPurpose` property it is said:

> Used to indicate a status message associated with a [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential). The status message descriptions MUST be defined in `credentialSubject.statusMessages`. `credentialSubject.statusSize` MUST be specified when this `statusPurpose` value is used.

I believe that since the Draft 16 April 2024, the `statusMessages` and `statusSize` have been moved from `BitstringStatusList` to `BitstringStatusListEntry`, right? Is this a mistake or should the `BitstringStatusListCredential` still contain those properties?

**Comment by timothee-haudebourg** [comment]
Hi @msporny, I see the `editorial` label was added, does that mean the `BitstringStatusList.statusSize` property has indeed been removed?

**Comment by msporny** [comment]
Hey @timothee-haudebourg, the group is currently focused on the other specifications and I was just trying to triage this issue. I've taken another look and agree with you, the current framing is problematic.

The issue with `statusSize` and `statusMessage` is that many of the current implementers have not implemented the feature yet or are not planning on implementing the feature. I think you've found an issue in the spec and agree with you that the placement of `statusSize` and `statusMessage` are problematic... we're going to keep repeating the same information when it probably belongs on the `StatusListCredential` -- I'm going to have to check w/ the people that created this feature and see why they wanted those properties on the status list entry instead of the status list credential. As a result, I'll re-label this as normative, as if we change this, it will be a normative change.

**Comment by dlongley** [comment]
For additional reasons why these pieces of information are in the status list entries in a VC and not the status list VC itself: https://github.com/w3c/vc-bitstring-status-list/issues/151

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-27-vcwg#section4-5) on 2024-09-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.5. The `BitstringStatusList.statusMessages` and `statusSize` properties are still being referenced (issue vc-bitstring-status-list#175)

_See github issue [vc-bitstring-status-list#175](https://github.com/w3c/vc-bitstring-status-list/issues/175)._




**Manu Sporny:** There is maybe only one implementer for this feature at this point.  

_See github issue [vc-bitstring-status-list#176](https://github.com/w3c/vc-bitstring-status-list/issues/176)._




**Manu Sporny:** Dont think it is currently marked as at risk.  
… Actually it is already marked at risk.  
… So we are waiting for implementations.  

**Brent Zundel:** My understanding is mesur implements these features.  

**Manu Sporny:** Great. I think Spruce may also be using it, so leaving it in awaiting implementations.  

</details>

**Comment by timothee-haudebourg** [comment]
I just want to point out that this change is affecting the vc-barcodes CCG where status list entries should be described in a compact way. Adding the statusMessages and statusSize properties would go against that. See https://github.com/w3c-ccg/vc-barcodes/issues/19

**Comment by msporny** [comment]
Yes, correct, the `statusSize` and `statusMessages` properties are not supported in vc-barcodes (due to encoding size restrictions in barcode formats). The placement of the `statusMessages` and `statusSize` properties were made after a variety of requirements were discussed and agreed upon in the WG. There are no plans to change the current design.

Please let us know if we're missing anything (I think we understand your concern and have responded to those concerns as best we can). I'm going to mark this issue as pending close and will get confirmation from the WG before closing it.
