### ISSUE TITLE
Status size missing from `BitstringStatusList`

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/vc-bitstring-status-list#176]
Hi, since the Draft 16 April 2024, the `status_size` property has been moved from `BistringStatusList` to `BistringStatusListEntry`. I understand it is sometimes necessary to know the status size from the entry without having to fetch the entire list, but removing it entirely from `BitstringStatusList` introduces some major issues in my opinion:
- It is now impossible to decode a status list without possessing a status list entry.
- The status size parameter must be passed around in many places of the implementation, making it error prone.
- This differs from IETF Token Status Lists, making it hard to implement a common API.

**Comment by msporny** [comment]
There is a related comment here for why the spec is in the state that it is in right now: https://github.com/w3c/vc-bitstring-status-list/issues/175#issuecomment-2355676039

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-27-vcwg#section4-5) on 2024-09-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.5. The `BitstringStatusList.statusMessages` and `statusSize` properties are still being referenced (issue vc-bitstring-status-list#175)

_See github issue [vc-bitstring-status-list#175](https://github.com/w3c/vc-bitstring-status-list/issues/175)._




**Manu Sporny:** There is maybe only one implementer for this feature at this point.  

_See github issue [vc-bitstring-status-list#176](https://github.com/w3c/vc-bitstring-status-list/issues/176)._




**Manu Sporny:** Dont think it is currently marked as at risk.  
… Actually it is already marked at risk.  
… So we are waiting for implementations.  

**Brent Zundel:** My understanding is mesur implements these features.  

**Manu Sporny:** Great. I think Spruce may also be using it, so leaving it in awaiting implementations.  

</details>

**Comment by timothee-haudebourg** [comment]
I just want to point out that this change is affecting the `vc-barcodes` CCG where status list entries should be described in a compact way. Adding the `statusMessages` and `statusSize` properties would go against that. See https://github.com/w3c-ccg/vc-barcodes/issues/19

**Comment by msporny** [comment]
Yes, correct, the `statusSize` and `statusMessages` properties are not supported in vc-barcodes (due to encoding size restrictions in barcode formats). The placement of the `statusMessages` and `statusSize` properties were made after a variety of requirements were discussed and agreed upon in the WG. There are no plans to change the current design.

Please let us know if we're missing anything (I think we understand your concern and have responded to those concerns as best we can). I'm going to mark this issue as pending close and will get confirmation from the WG before closing it.
