### ISSUE TITLE
Handling Right to Erasure in encodedList and Validate Algorithm

### ISSUE THREAD

**Issue by sbutterfield** [w3c/vc-bitstring-status-list#23]
EU Regulatory and CPPA interpretation of an individual's rights to privacy related to the Right to Erasure present a pathological condition to the general revocation/suspension feature of a Verifiable Credential. Consider the following:

- Bob is a French Citizen, Acme Co is a German Employer
- Bob's VC is revoked by Acme Co (for whatever reason)
- Acme Co recomputes the revocation bitstring associated with the published StatusListCredential and performs the appropriate issuing steps to the trust registry, now verifiers can assert that Bob's VC is revoked.
- Bob still attempts to present his credential and is annoyed its revoked. Bob decides to invoke his GDPR individual privacy rights and demands that Acme Co erase all information they have about Bob. Under the aforementioned regulatory oversight bodies, this ***includes Bob's statusListIndex related to his VC, and the associated published content relating to or referencing that statusListIndex value***
- So, Acme Co is forced to either: (a) comply, and by doing so and recomputing the revocation bitstring again - makes Bob's credential once again verifiable by nature of the `Validate Algorithm` current implementation ... or (b) decide not to comply with revocation bitstring recomputation, keeps Bob's bit on the string. In which case, Bob tries to present his credential, it shows up as revoked, now Bob can take Acme Co to court and win a settlement (again, under current regulatory interpretation).

Whilst this scenario is admittedly considered an edge case, it is an ongoing regulatory and privacy challenge with immutable data stores and some of the design constructs built into VC specifications. This is a formidable challenge to an implementor's ability to support privacy-preserving and regulatory compliant revocation/suspension. 

I've tried considering some options to resolve, but each time I end up disqualifying them. Putting this up to circulate for feedback @msporny

**Comment by msporny** [comment]
> Whilst this scenario is admittedly considered an edge case, it is an ongoing regulatory and privacy challenge with immutable data stores and some of the design constructs built into VC specifications.

So, we need a *real* legal interpretation of what I'm about to say here. These topics are like catnip to some folks in the community, and we should remember that if the person speaking isn't a lawyer, and well versed in privacy law, I expect them to be very out of their depth on this particular question. Myself included. I am not a lawyer.

That said (armchair lawyering below):

I've had variations of this discussion with legal counsel and one thing that kept coming up is to remember that privacy law doesn't happen in a vacuum, and if the erasure of information could cause societal harm, that is taken into account (and the harms to society usually trump any harm to an individual). Think about a criminal invoking this to get all of their records that they were a criminal expunged via GDPR -- it just wouldn't fly.

The other thing to consider here is that if it is true that the individual wants to invoke the right of erasure, and the organization has expunged all relevant PII (except for the status bit for revocation), then the individual is the only one that's left that is holding on to the PII; so, they should delete their credential. You don't have to touch the status bit to meet the right to erasure bar.

If the service provider deletes all PII, leaving the bit in the bitstring in place, that meets the request while simultaneously not "unrevoking" the credential. At that point, the bit is set to 1 (revoked), but it is completely detached from the original credential (remember, the service provider delete all the PII, and presumably, so did the individual making the request (except, really, they were lying). That is, there is no way to correlate (other than via the credential the individual that has asserted the right to erasure is holding). That should meet the requirements, set by GDPR and other privacy laws, for the right to erasure.

If you find this argument compelling, we should probably write this up in the Security Considerations section.

**Comment by sbutterfield** [comment]
It'd be great to connect live on this for a little bit. Just want to say, in practice, I agree with everything you've said. This issue is 🔥 🔥  and I don't mean to fire shots or anything - but the question does honestly come out of some long and difficult conversations with regulators already.

> So, we need a real legal interpretation of what I'm about to say here. These topics are like catnip to some folks in the community, and we should remember that if the person speaking isn't a lawyer, and well versed in privacy law, I expect them to be very out of their depth on this particular question. Myself included. I am not a lawyer.

Totally agree. I am not one either 😆 , but there is some pretty considerable legal and regulatory outreach that has been done to generate this inquiry

> Think about a criminal invoking this to get all of their records that they were a criminal expunged via GDPR -- it just wouldn't fly.

💯 ! The bar for societal harm being interpretable situationally, but I take your point. Credit scores as VCs are an interesting test-case here where the immediate social harm burden-of-proof would fall to the controller of the bitstring and bit position to establish that it does cause harm for them to leave the bit on the bitstring in place.

> then the individual is the only one that's left that is holding on to the PII; so, they should delete their credential. You don't have to touch the status bit to meet the right to erasure bar.

I'm exploring this further, but so far it hasn't been fully tested to my knowledge. If the bitstring is published by Acme Co. (even on a permissioned, decentralized immutable ledger) then they are a Data Controller under GDPR. A `statusListIndex` value is technically PII and correlatable to Bob's credential by any agent performing `Verify Algorithm` action upon presentation (per the algorithm, claims read and verified prior to bitstring expansion). 
One of the problems is the GDPR definition of PII. Some legal analysts posit based on some GDPR discussion that a crypto digest of PII _or any unique identifier that can be correlated to PII is PII._

> If the service provider deletes all PII, leaving the bit in the bitstring in place, that meets the request while simultaneously not "unrevoking" the credential. At that point, the bit is set to 1 (revoked), but it is completely detached from the original credential (remember, the service provider delete all the PII, and presumably, so did the individual making the request (except, really, they were lying). That is, there is no way to correlate (other than via the credential the individual that has asserted the right to erasure is holding). That should meet the requirements, set by GDPR and other privacy laws, for the right to erasure.

Definitely the most compelling and useful presentation related back to the example. Thanks for this 🤝 .

IMHO, I think this a really special topic and really warrants some kind of write-up in the spec as it would help early adopters grapple with privacy law. I'd be thrilled to help with this in any way that I can.

**Comment by msporny** [comment]
@sbutterfield wrote:
> A `statusListIndex` value is technically PII and correlatable to Bob's credential by any agent performing `Verify Algorithm` action upon presentation (per the algorithm, claims read and verified prior to bitstring expansion).

This is only true IF more than just the holder has the original VC. If the original VC is deleted from the Data Controller, the bit in the bitstring ceases to be PII because it's a 0 or a 1, and is in no way correlatable back to the original subject.

Now, you could argue "But what about all the people out there that are holding on to the original VC for the purposes of ensuring proper audit records!", which is a valid counter-argument. I have no idea how legal interpretation is going to go down wrt. GDPR and that particular item. It might fall into the "we can't police the world" category OR the VC might point to a "GDPR take down" list that can notify everyone if the original subject has asserted a right to erasure... yet another status list, but this one broadcasts to the world: "Beware, the subject has asserted GDPR right to erasure on this VC, if you have it in your system, expunge it!". The sloppiness of GDPRs language is going to continue to cause issues for anyone dealing with credentialing systems... it's not inherent to VCs... it's /any/ credentialing system. We just happen to have some workable, if not semi-complex to implement properly, solutions.

> One of the problems is the GDPR definition of PII. Some legal analysts posit based on some GDPR discussion that a crypto digest of PII _or any unique identifier that can be correlated to PII is PII._

Yes, even for salted hashes, which is ludicrous, but here we are. This is the problem w/ well-meaning, but sloppy legislation. In any case, the courts will be trying to figure these things out over the next 10-20 years, all we can do is provide some reasonable options and input for the courts.

**Comment by msporny** [comment]
@sbutterfield wrote:
> IMHO, I think this a really special topic and warrants some kind of write-up in the spec as it would help early adopters grapple with privacy law. I'd be thrilled to help with this in any way that I can.

PRs welcome.

Just raise a PR against this spec, keep it small-ish and focused (2-4 paragraphs to start, tops), model it after these sections in the VC Data Model Spec:

https://www.w3.org/TR/vc-data-model/#privacy-considerations

and just capture our discussion above for the first iteration of the PR.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-24-vcwg-special#section1-5) on 2023-01-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.5. Handling Right to Erasure in encodedList and Validate Algorithm (issue vc-status-list-2021#23)

_See github issue [vc-status-list-2021#23](https://github.com/w3c/vc-status-list-2021/issues/23)._




**Kristina Yasuda:** issue 23.  
… It's a tricky, legal oriented discussion. Last comment said ready for PR.  
… Is it?.  
… Shawn?.  

**Shawn Butterfield:** This is something I raised early on..  
… I have a set of privacy legal experts I can task to help make a PR.  
… Happy to take this on.  

**Manu Sporny:** I think this is ready for PR, Shawn if you can move this forward with legal experts, that would help.  

> *Shawn Butterfield:* Sounds good.

**Kristina Yasuda:** thanks shawn. added Ready for PR.  

</details>

**Comment by msporny** [comment]
We have seen no movement on this issue or a PR to address it in about a year. Authoring a PR would require a legal interpretation of some subset of privacy laws and regulations (which are inherently region-dependent).

I see no way forward on this issue unless legal counsel were to get involved in drafting language. At present, there doesn't seem to be any interest in doing so in the VCWG. I'm marking this issue as "pending close". It will be closed within the next week or two unless someone can step up and write a PR that addresses the issue.

**Comment by TallTed** [comment]
I think this is more accurately "not planned" than "completed"... and we should try to be accurate in these status changes, to ease future effort.
