### ISSUE TITLE
Status of what?

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-bitstring-status-list#35]
There is some confusion about the semantics of the credentialStatus field, whether it refers to the status of the credential or the verifiable credential. (see https://github.com/w3c/vc-data-model/issues/991) Clearly both the underlying credential (e.g. degree certificate) and the digitally signed VC have their own separate validity periods and statuses. This confusion is carried through into the status list specification in that the statusPurpose in not precise enough. 
It has been stated that vc-status-list-2021 can apply to both the credential and the verifiable credential, in which case the statusPurpose must clearly specify to which of these this list applies.
The follow values for statusPurpose are suggested

credentialRevocation - the credential has been revoked (even though the cryptographic proof of the verifiable credential is still valid)
proofRevocation - the cryptographic proof of the verifiable credential has been revoked. This does not imply that the enclosed credential has been revoked, only that the verifiable credential has been revoked. The status of the credential is unknown.
credentialSuspension - the credential has been suspended. This may be reversed at a later time.

I am not sure it makes sense to have a proofSuspension. What does this mean and when would it apply?

**Comment by msporny** [comment]
Quite a bit has happened in the VCDM since this issue was raised. The VCDM now only defines what constitutes a "verifiable credential". The status field for a "verifiable credential" has to do with whether or not the "verifiable credential" has been revoked or not. This might be for any reason, and just because the "verifiable credential" has been revoked doesn't mean that the underlying credential is revoked. That said, if the "verifiable credential" has been revoked, then it shouldn't be used to drive any business process that requires the "verifiable credential" to not be revoked (or suspended).

I will add some explanatory text about this in a PR.

**Comment by msporny** [comment]
PR #106 has been raised to address this issue. This issue will be closed once PR #106 has been merged.

**Comment by msporny** [comment]
PR #106 has been merged, closing.
