### ISSUE TITLE
Specify bit order for status list 

### ISSUE THREAD

**Issue by msporny** [w3c/vc-bitstring-status-list#36]
We need to add text to the specification that notes that the bit order for bitstring, namely in an array of bits from 0..N, the left most bit is index 0, and the right most bit is index N. This is not to be confused with big-endian vs. little-endian byte order.

**Comment by dlongley** [comment]
Specifically, the left most bit of a bitstring is the first bit (index 0) and the right most bit is the last bit.

**Comment by Sakurann** [comment]
+1. 

> the left most bit of a bitstring is the first bit (index 0) and the right most bit is the last bit (index length - 1). It may be better to describe it this way to avoid confusing byte order with bit order and so on. 

this explanation would be very very helpful. We have faced a case where the issuer's revocation service and the verifiers service had different implementations and were checking the wrong bit for revocation.

**Comment by TallTed** [comment]
> some example images would also be helpful.

Yes, please. I think I understand intent, but I'm not sure.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-24-vcwg-special#section1-4) on 2023-01-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. Specify bit order for status list  (issue vc-status-list-2021#36)

_See github issue [vc-status-list-2021#36](https://github.com/w3c/vc-status-list-2021/issues/36)._




**Kristina Yasuda:** ten minutes left. one more issue #36.  

**Manu Sporny:** yes, we should do this.  
… we already have examples of implementers interpreting this differently. Ready for PR.  

**Kristina Yasuda:** any objections?.  
… [none were heard].  

> *Brent Zundel:* I would call them processing rules. Once processed, the Verifier can still determine whether the information applies to its internal validation rules..

</details>

**Comment by msporny** [comment]
PR #45 has been raised to address this issue. This issue will be closed once PR #45 has been merged.

**Comment by msporny** [comment]
PR #45 has been merged, closing.
