### ISSUE TITLE
Status-List-2021 without the VC

### ISSUE THREAD

**Issue by sloops77** [w3c/vc-bitstring-status-list#4]
Hi all,
I am working on the velocity network which is a SSI network focussed on individual careers. 

We are basing our implementation of revocation on status-list 2021

We were looking at storing the bitlist under an ethereum account each of our issuers has. The zipping and embedding it in a VC elements seem unnecessary if we are using ethereum.  The bitlist can be retrieved using an ethereum uri https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md. Additionally we are looking at retrieving the status directly from the chain by calling a contract function that also takes the bitlist index, and returns status directly. To my understanding the privacy of the holder is still intact in using either contract function. The blockchain reads cannot be monitored by the issuer. 

It has these benefits 
  - updating single elements or in bulk is supported and more efficient than having to revoke and resign VC each time an update happens
  - it will continue to function even if an issuer becoming bankrupt, or closed down as the data is on chain
  - it takes advantage of the underlying world-state compression engine (snappy)
  - proofs are redundant since an account signing key is required to set or update the account's data.

So i would appreciate any feedback:
- Are these benefit fairly stated?
- We are looking to be standards compliant as much as we can. I dont want to presume to change the standard, but at the same time offhand i dont see an easy way to snap our proposed solution to it.

**Comment by kezike** [comment]
Thanks for sharing @sloops77! One comment I have is on status timeliness: if you are storing the bitlist in an Ethereum account, there will necessarily be a lag between the moment an issuer initiates an update to the bitlist and the time it is resolved by consensus. This will roughly be the best-practice value for total wait time based on Ethereum transaction confirmation time => `CONF_TIME × NUM_CONFS` on the Ethereum network. As the system designer, you should make this clear in the system's SLA.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-31-vcwg-special#section2-1) on 2023-01-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Status-List-2021 without the VC (issue vc-status-list-2021#4)

_See github issue [vc-status-list-2021#4](https://github.com/w3c/vc-status-list-2021/issues/4)._




**Brent Zundel:** sounds like the poster is seeking information.  


**Kristina Yasuda:** seems like a question that could impact spec design.  
… there was an option for the bitmap to be in a did doc before.  
… can it be made legal to put the bitmap list in a did doc?.  
… we could discuss.  

**Manu Sporny:** technically, you can use a status list URL, including a DID....  
… dereferencing must be a VC currently, so a DID Document would not be secured..  
… we don't currently have a way to support hosting the list in a did document.  
… I am concerned about expanding the scope of a status list.  
… I know its possible to create URLs that would work for this..  

**Kristina Yasuda:** I don't have strong opinions either way, does an object that is stored under a URL or a DID... does it have to be signed?.  
… if you trust the PKI, does it still need to be signed?.  
… maybe the answer is you sign anyway....  
… from interop perspective, less options the better.  
… can the result be a simple JWS?.  
… seems like maybe folks should not need to understand the VC spec to process the status list.  

**Manu Sporny:** if we don't sign it, they you do need to trust the domain / did method / web host / did controller ... etc....  
… we could say, it does not need to be signed, just make sure its secured..  
… then it opens the attack surface on the integrity of the list.  
… why a vc? the reason they go to the list, is because they are coming from a VC... we know they can already process VCs..  
… its not a surprise for he implementer to get another VC..  
… could the list be signed differently, but then we have mixed technologies for the list and the original vc.  
… for those reasons we built it on top of VCs.  

**phil ASU:** also concerned about the attack surface, but also concerned about multiple ways to achieve the same objective..  
… if they can already handle a VC, we should ask them for clarity regarding why they are asking the question regarding ethereum.  

> *Kristina Yasuda:* "The statusListCredential property MUST be a URL to a verifiable credential." should be changed to "URI".

> *Kristina Yasuda:* if DIDs, ethereum URLs are to be allowed.

**Orie Steele:** Manu covered a lot of what I would say. I think it's a mistake for a credential status type to have a lot of agility on the security format. It seems ok to me to have the URL structure be one of any possible valid URLs that dereference to a VC. The DID side of it I don't have strong objections to..  
… However, switching to a different cryptographic suite from what the VC uses, it could make the end verifier implement multiple cryptosuite to implement a revocable credential, don't think that's a good thing. If the objective is to store the list on a blockchain, on a website or without security... each of those are separate items and it's possible that they could all be well supported if they all have a unique type and they're supported separately..  
… I think it's a mistake to expand the scope of status list to do all of those things..  

**Manu Sporny:** one use case to mention, on why do we sign....  
… signing enables offline presentation by the holder.  
… this allows for revocably credentials to be presented without going to the network.  
… this can also enable the verifier to not need to make network requests.  
… the holder may present the list directly to the verifier.  

> *Phil ASU:* +1 for preserving the holder providing the status list directly to the verifier..

**Kristina Yasuda:** thanks for the comments.  
… it would be good to clarify the answers to these questons.  
… should it be URI instead of URL ?.  

> *Manu Sporny:* agree that we should clarify all of these things in the spec... I don't think we say many of these things..

> *Michael Prorock:* url is new syntax via whatwg.

**Manu Sporny:** normally we would have put URI, but there was a big fight over URI vs URL and WHATWG.  
… so we should call everything a URL.  
… so now we call everything a URL.  

> *Michael Prorock:* manu schooled the sh*** out of me on this and i still have bad habits on uri etc.

> *Kristina Yasuda:* that's the answer i expected.

**Manu Sporny:** we can't call them URIs or we will get yelled at by WHATWG.  

> *Andres Uribe:* That just underscores why url should be used everywhere :P.

**Brent Zundel:** any next steps that need to go into the issue?.  

**Manu Sporny:** kristina asked for us to clarify in the spec on this, and we should..  
… we should add a PR to comment on what we have just discussed.  

> *Michael Prorock:* +1 manu - spec is good if you "know" not as good if you don't.

> *Kristina Yasuda:* (and I think the answer to issue #4 is they would have to host a VC under an ethereum URL).

</details>

**Comment by OR13** [comment]
Suggest closing

**Comment by msporny** [comment]
@sloops77 a lot of time has passed since this initial comment. The VCWG is in the final push to finish this specification for the Candidate Recommendation phase. Some answers to your questions below:

> Are these benefit fairly stated?

Yes, the benefits are fairly stated. That said, the goals of placing the status list that is defined by this specification is not a design goal. It is true that portions of the mechanisms used in the specification could be used in the way you state it, but the approaches you mention would require a significant re-working of the specification that I doubt would achieve consensus in the current VCWG (based on our current trajectory and timeline).

> We are looking to be standards compliant as much as we can. I dont want to presume to change the standard, but at the same time offhand i dont see an easy way to snap our proposed solution to it.

Yes, it's not an easy change/fix to the specification. I expect that a different type of status list specifically designed for the Ethereum blockchain would be in order. That would slot into the Verifiable Credentials data model fairly easily as just another type of status list mechanism.

**Comment by msporny** [comment]
There is no action that the VCWG could take on this issue that would result in an Ethereum-compatible solution. The proposed path forward is for another status list mechanism to be created that would be focused on publishing the status list on the Ethereum blockchain. Closing.
