### ISSUE TITLE
Clarify that `StatusList2021Credential` must be VC-DATA-MODEL (v1.1)

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-bitstring-status-list#51]
> The constraints on the id property are listed in the Verifiable Credentials Data Model specification [[VC-DATA-MODEL](https://w3c.github.io/vc-status-list-2021/#bib-vc-data-model)].

this is the only place that says that `StatusList2021Credential` must be [[VC-DATA-MODEL](https://w3c.github.io/vc-status-list-2021/#bib-vc-data-model)] (v1.1).

We should clarify this in the description of Section 2.2 StatusList2021Credential

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-15-vcwg#section1-9) on 2023-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.9. Clarify that `StatusList2021Credential` must be VC-DATA-MODEL (v1.1) (issue vc-status-list-2021#51)

_See github issue [vc-status-list-2021#51](https://github.com/w3c/vc-status-list-2021/issues/51)._




**Manu Sporny:** clarify if VC data model, what are we targeting?  

**Kristina Yasuda:** clarification i'm looking for is the shape of a status list.  
… examples using VC data model, but no where in the doc it says that it must be compliant.  
… is it reallly the VC data model?  
… doesn't seem like it needs to be compliant with the VC data model.  
… doesn't have info about the holder ...  
… sitting on a HTTPS url.  
… i'd prefer if this was a simple JWT.  
… not sure if i can convince this group to go in this direction.  
… so looking for clarity.  

**Manu Sporny:** yeah ... it is definitely VC data model.  

> *Kristina Yasuda:* like what?

**Manu Sporny:** we rely on a variety of things, in the status list.  
… there is a use case where the holder takes this.  
… for the purposes of privacy protections.  
… so that the verifier doesn't have to go out and fetch it.  
… to be clear, we depend on things like the issuer ... valid from and valid until ... credential subjects ...  
… not easy to put into a JWT.  
… that said, you can encode it into a JWT.  
… but the data model, it is highly dependent on the VC data model.  

**Joe Andrieu:** first i thought that made sense kristina, but then realized that ...  

**Kristina Yasuda:** the way i differentiate it ... it is independent of the data model of how the status list is expressed ...  
… for example, if there is a CBOR based credential.  
… technically, the status list doesn't need to be CBOR.  
… i've seem people doing that.  
… there is a sepearation of HOW things are expressed and WHAT things it epxresses.  

</details>

**Comment by msporny** [comment]
PR #102 and #108 have been raised to make it explicit that this specification depends on VCDM v2.0.

**Comment by msporny** [comment]
PRs #102 and #108 have been merged, closing.
