### ISSUE TITLE
Implementation Considerations

### ISSUE THREAD

**Issue by shigeya** [w3c/vc-bitstring-status-list#56]
I have multiple concerns about the current proposal.

The current specification states the use of GZIP for compression for the whole bitstring. This algorithm compresses bitstring into a series of Huffman-compressed blocks. I agree this is a reasonable choice from the size-efficiency point of view.

However, I think the current discussion lacks some implementation considerations. This includes where the entire list is kept and how the verifier efficiently accesses a revocation bit. Will the verifier need to retrieve the whole status list? I understand we are discussing this in a technology-neutral manner as far as possible. Still, we need to consider implementation details if we start discussing how to treat bits and compression.

There are two points of view I want to share here.

## The expected transaction model does not match blockchain-like storage

This scheme (compressing the entire bitstring) is unsuitable if the maintainer wants to record the status list data onto a blockchain-like ledger. We can't know how frequently the maintainer will update the list. In a worst-case scenario, the maintainer must continuously replace the entire status list on the storage. This is acceptable for a typical file system since replacement of the file contents is almost zero cost. But for a blockchain-like ledger, the cost will be hard to ignore.

From this point of view, I think how the data model looks and how the bits are stored need to be discussed separately.

## The memory and storage requirements

It looks like there is an assumption of the model using the list to fetch the entire list, verify, uncompress, and find a bit. From a client who wants a single bit, this is not acceptable if the size of the status list is considerably large. Some numbers are mentioned in the current specification, but are these assumptions safe? Do we need to have another specification support a large number of certificates?  For example, with GZIP, the decoder needs to keep the Huffman tree in the block header in memory.  Suppose the memory footprint for a verifier runtime on an IoT device needs to be very low. In that case, the verifier code needs to scan the bitstring while decompressing the sequence of blocks one by one, not just decompress and read a bit. Depending on the environment, this can be a real headache.

While the use of bitstring is attractive from a privacy point of view, we need to find a better way to serialize and compress the data.

**Comment by msporny** [comment]
> Will the verifier need to retrieve the whole status list? 

Yes, they will. Keep in mind that the status list can be "chunked" into multiple lists. For example, if you have a population of 1 million entities, you can "chunk" the population into 10 lists of 100,000 entities. That way, any particular verifier downloading a list need only download 1/10th of the full list size.

> ## The expected transaction model does not match blockchain-like storage

The design of Bitstring Status List does not take storage on a blockchain into account. If blockchain-based storage is desired, a different "Blockchain Status List" mechanism could be created and used instead. 

> We can't know how frequently the maintainer will update the list. 

Yes, how often the list is updated will be use case dependent.

> This is acceptable for a typical file system since replacement of the file contents is almost zero cost.

Yes, that is the sort of deployment model that this is designed for.

> But for a blockchain-like ledger, the cost will be hard to ignore.

Yes, the cost will be more, which probably warrants a different design approach (and a different specification).

> It looks like there is an assumption of the model using the list to fetch the entire list, verify, uncompress, and find a bit. From a client who wants a single bit, this is not acceptable if the size of the status list is considerably large. 

Note (above) that the lists can be chunked to fairly small sizes.

> Some numbers are mentioned in the current specification, but are these assumptions safe?

We believe the assumptions are aligned with the current use cases that the solution is designed for.

> Do we need to have another specification support a large number of certificates?

No, mostly because of the "chunking" design above. Using a single bit to store the value is as small as we can get (from a computation standpoint). 

> For example, with GZIP, the decoder needs to keep the Huffman tree in the block header in memory. Suppose the memory footprint for a verifier runtime on an IoT device needs to be very low.

We would need someone deploying a real use case to production to understand the memory constraints of the device that is processing the status list. At present, it's assumed that the IoT device is at least as capable as a Raspberry Pi Zero ($15 IoT-capable device). 

> In that case, the verifier code needs to scan the bitstring while decompressing the sequence of blocks one by one, not just decompress and read a bit. Depending on the environment, this can be a real headache.

Sure, but if you're dealing w/ a environment that is that constrained, it's the only path forward. 

> While the use of bitstring is attractive from a privacy point of view, we need to find a better way to serialize and compress the data.

We would need someone to commit to designing, implementing, creating a test suite for, and deploying an alternate into production. At present, other alternate mechanisms have not been proposed.

That is not to say that other designs and goals are not possible; they are, it's just that the group would have to put significant effort into an alternate path and it does not seem like that will be viable given that we are attempting to take this specification into the Candidate Recommendation phase in under a month.

**Comment by msporny** [comment]
I'm marking this issue as pending close, as the questions have been answered and it's unlikely that we are going to have a significant design shift at this point in the standardization process.

**Comment by shigeya** [comment]
While I still have multiple questions with your answers, I understand the necessity to proceed with this document.

**Comment by msporny** [comment]
@shigeya wrote:
> While I still have multiple questions with your answers

Perhaps we can continue the discussion here, or you could raise new issues w/ your questions so we can track/discuss.
