### ISSUE TITLE
Encoded list in Base64 or Base64Url?

### ISSUE THREAD

**Issue by amondit** [w3c/vc-bitstring-status-list#58]
Hello,

The spec mentions that the status list must be distributed as gzip'd bitstream in base64 (section 2.2). However the example contains a `-` character which is only supported in Base64Url (regular decoding in base64 of this example fails).
Could you clarify whether we should use base64url encoding, or fix the example in the draft documentation?

Best regards,
Arnaud

**Comment by OR13** [comment]
base64url, to align with the rest of jose tool chain for securing JSON.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-15-vcwg#section1-5) on 2023-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.5. Encoded list in Base64 or Base64Url? (issue vc-status-list-2021#58)

_See github issue [vc-status-list-2021#58](https://github.com/w3c/vc-status-list-2021/issues/58)._




**Manu Sporny:** lets do 58 next.  
… should we use base64 or base64url to encode the list.  
… orie says we should say base64url, anyone opposed?  

**Brent Zundel:** no one on the queue, you are good to go.  

**Manu Sporny:** neat, i can take it.  

</details>

**Comment by msporny** [comment]
PR #110 has been raised to address this issue. This issue will be closed once PR #110 has been merged.

**Comment by msporny** [comment]
PR #110 has been merged, closing.
