### ISSUE TITLE
TAG Review Request -- Submitted

### ISSUE THREAD

**Issue by mkhraisha** [w3c/vc-bitstring-status-list#72]
I'm requesting a TAG review of Verifiable Credential Status List 2021.

This specification describes a privacy-preserving, space-efficient, and high-performance mechanism for publishing status information such as suspension or revocation of Verifiable Credentials.

  - Explainer¹ (minimally containing user needs and example code): [Explainer](https://github.com/w3c/vc-status-list-2021/blob/main/explainer.md)
  - Specification URL: [Verifiable Credential Status List 2021](https://w3c.github.io/vc-status-list-2021/)
  - Tests: [Test Suite WIP](https://w3c-ccg.github.io/status-list-2021-test-suite/)
  - User research: N/A
  - Security and Privacy self-review²: [Security and Privacy Self-Review](https://github.com/w3c/vc-status-list-2021/issues/77)
  - GitHub repo (if you prefer feedback filed there): [VC Status List Github](https://github.com/w3c/vc-status-list-2021/)
  - Primary contacts (and their relationship to the specification):
      - Brent Zundel (@brentzundel), VCWG Chair, Gen
      - Kristina Yasuda (@Sakurann), VCWG Chair, Microsoft
      - Manu Sporny (@msporny), Editor, Digital Bazaar
      - Dave Longley (@dlongley), Editor, Digital Bazaar
      - Orie Steele (@OR13), Editor, Transmute
      - Mike Prorock (@mprorock), Editor, Mesur.io
      - Mahmoud Alkhraishi (@mkhraisha), Editor, Mavennet
  - Organization(s)/project(s) driving the specification: [W3C Verifiable Credentials Working Group](https://www.w3.org/2017/vc/WG/)
  - Key pieces of existing multi-stakeholder review or discussion of this specification: n/a
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): [Issue Tracker](https://github.com/w3c/vc-status-list-2021/issues/)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines:

 The VCWG is planning to take this specification to Candidate Recommendation in September 2023 (at W3C TPAC), reviews before that time frame (ideally, by the end of July 2023) would be ideal.

  - The group where the work on this specification is currently being done: 
[W3C Verifiable Credentials Working Group](https://www.w3.org/2017/vc/WG/)
  - Major unresolved issues with or opposition to this specification:

 The specification is undergoing work to address definition and reference of multiple status beyond suspension and revocation.

  - This work is being funded by: The members of the W3C VCWG that are actively participating in the development of these specifications including funding from the US Federal Government, the European Commission, and the Canadian Federal Government

You should also know that this work intersects heavily with the Verifiable Credentials v2.0 work, which is also something that the TAG will be actively reviewing around the same time

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  ☂️ open a single issue in our GitHub repo **for the entire review**

**Comment by msporny** [comment]
The TAG issue is being tracked here: https://github.com/w3ctag/design-reviews/issues/874

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-16-vcwg-special#section2-1) on 2024-01-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. TAG Review Request -- Submitted (issue vc-bitstring-status-list#72)

_See github issue [vc-bitstring-status-list#72](https://github.com/w3c/vc-bitstring-status-list/issues/72)._




**Brent Zundel:** Moving to our first issue. Goal is to share status, and to help forward as needed.  
… have we heard back from TAG?  

**Manu Sporny:** I don't know. I was going to say 72 and 77 are tracking issues.  
… We requested back in July. So we can proceed as they've timed out.  

**Brent Zundel:** the request in the TAG github that was raised, it would be good to link to this issue.  

> *Manu Sporny:* See [Relevant TAG issue](https://github.com/w3ctag/design-reviews/issues/874).

**Manu Sporny:** It's been reviewed already.  
… They asked for pointers, we responded. They're asking to schedule time in the f2f in London.  

**Brent Zundel:** Good. Moving on.  

</details>

**Comment by msporny** [comment]
w3ctag/design-reviews#874 has been closed as completed, closing this tracking issue as a result.
