### ISSUE TITLE
auto-publishing using echidna?

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-bitstring-status-list#82]
I thought that all of the work items adopted by the VCWG had resolved to use Echidna to auto publish, but I'm not seeing an updated version at https://w3c.github.io/vc-status-list-2021/
Is this a known issue?

**Comment by TallTed** [comment]
> The (painful) changes we made with jose-cose shows what has to be done if we want to get it right ... [which] is just too much hassle at this point

I sympathize with this, but even though URIs (and arguably, document short names) should be opaque (as I often vocalize), there is (and will be, for a long time to come) significant difference between what humans will read into `vc-bit-string-status-list` and `vc-status-list-2021`, and that difference will bite many over time.

I think the change is worthwhile.

I have hopes that the recent experience of having done this for `jose-cose` left a track that can be retraced for `bit-string-status-list` (and *maybe* written up for future humans who may need to do similar in/for other WG documents).

**Comment by OR13** [comment]
Happy to help however I can, but unfortunately there are some things only staff can do regarding name changes.

**Comment by iherman** [comment]
Yeah, *if* the WG decides to do this, then we can of course go through.

Just for the records in case we do this:

- see https://github.com/w3c/vc-jose-cose/pull/115#issuecomment-1620408736 for what has to be done process wise
- see https://github.com/w3c/vc-jose-cose/pull/125#issuecomment-1633943671 for some more comments on what/how to manage some details

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-15-vcwg#section1-3) on 2023-09-15

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-15-vcwg#resolution1):  the new shortname is `vc-bitstring-status-list`.***

<details><summary><i>View the transcript</i></summary>

#### 1.3. auto-publishing using echidna? (issue vc-status-list-2021#82)

_See github issue [vc-status-list-2021#82](https://github.com/w3c/vc-status-list-2021/issues/82)._



**Brent Zundel:** intro, spec from april, fix for this is straightfoward, we need to go back to call vc status 2021 ... unless we as a group change the record name ...  


**Brent Zundel:** we either change it back or we have a formal resolution to change the name ...  
… ivan and the editors ...  

**Manu Sporny:** just need to change the name of the spec ... no longer vc status list 2021 ... use something less generic.  

> *Dmitri Zagidulin:* @TallTed - sure, that's business logic. I'm just wondering why you're saying "VCs weren't designed for this". business logic is a huge part of VC validation, it's absolutely designed for it.

**Manu Sporny:** maybe vc multi status list ... vc stream status list ...  
… hesistant to change it today.  
… interested in time boxing it.  

**Brent Zundel:** 2 mins.  
… if something can come up with a good name in the next 2 mins.  

> *Andres Uribe:* I like`vc-bit-string-status-list`.

**Kristina Yasuda:** why is this so complicated? why can't we just remove 2021 from the name?  

**Brent Zundel:** that would work.  

> *Manu Sporny:* -1.

> *Gabe Cohen:* +1.

> *Dmitri Zagidulin:* +1.

**Brent Zundel:** would that work for everybody?  
… anyone opposed?  

**Manu Sporny:** yes, too generic.  

> *Andres Uribe:* 0 (prefer `vc-bit-string-status-list`).

**Manu Sporny:** bit string status list.  

**Brent Zundel:** anyone opposed?  

**Kristina Yasuda:** i do think you need status list of "what"?  

**Brent Zundel:** no one wants to die on the hill.  
… i'll draft a proposal.  

**Manu Sporny:** there is also ... nevermind.  

> *Kristina Yasuda:* what was manu's proposal?

**Joe Andrieu:** seems like misalignment between two names ...  

**Ivan Herman:** lets not rename the doc in three months ... lets do them both at the same time ...  

> **Proposed resolution: the new shortname is `vc-bitstring-status-list`.** *(Brent Zundel)*

> *Manu Sporny:* +1.

> *Gabe Cohen:* +1.

> *Joe Andrieu:* +1.

> *Shigeya Suzuki:* +1.

> *Ivan Herman:* 0.

> *Dmitri Zagidulin:* +1.

> *Andres Uribe:* +1.

> *Brent Zundel:* +1.

> *David Waite:* +1.

> *Ted Thibodeau Jr.:* +0.

> *Hiroyuki Sano:* 0.

> *David Chadwick:* +1.

> *Kristina Yasuda:* 0.

> *Jay Kishigami:* 0.

> *Paul Dietrich:* 0.

> ***Resolution #1: the new shortname is `vc-bitstring-status-list`.***

**Brent Zundel:** not seeing any opposition.  
… we are resolved.  
… practical level, who is going to fix the spec.  

**Ivan Herman:** who wants to help?  

**Manu Sporny:** i can help.  
… i can do the naming changes.  

**Ivan Herman:** i have put a comment into the issue where i summarized what we need to do in the COSE/JOSE change.  

**Brent Zundel:** good conversation ... we still have like 25 issues to look at.  
… and 30 mins to do it.  
… if the editors have preferences for how to prioritize ...  
… take advantage of the people in the room.  
… jumping into 81.  

**Manu Sporny:** skip that.  

</details>

**Comment by iherman** [comment]
The WD has been published under the new short name, i.e., https://www.w3.org/TR/vc-bitstring-status-list/. A PR has been raised for the proper changes of echidna (see #95). I propose to close this issue as settled.

cc @brentzundel

**Comment by msporny** [comment]
@iherman auto-publishing isn't working because the publishing token is invalid for some reason:

https://github.com/w3c/vc-bitstring-status-list/actions/runs/7349609343/job/20009850064#step:3:683

https://labs.w3.org/echidna/api/status?id=7c84e63d-317a-45ad-ab2d-17aa48928fee

I believe auto-publishing will work again once the Echidna token is updated/set.

**Comment by iherman** [comment]
@msporny I have generated a new secret token (the one in the repository was bound to the previous short name...), and refreshed the value in github. Can you test again?

**Comment by iherman** [comment]
Well... no idea then. This is @deniak territory...

Denis, help! :-(

**Comment by deniak** [comment]
I'm not sure what happened but I updated the token in GH and I re-triggered the [action which passes now](https://github.com/w3c/vc-bitstring-status-list/actions/runs/7360073023/job/20237331602).

**Comment by iherman** [comment]
Well... echidna needed your personal touch, @deniak...

Thanks!

**Comment by msporny** [comment]
This issue has been resolved, closing.
