### ISSUE TITLE
Cascading status updates

### ISSUE THREAD

**Issue by OR13** [w3c/vc-bitstring-status-list#84]
We have a use case where suspension of a root credential should cause ___validation___ of a child credential to fail.

Is this a case that others have?

Has there been any discussion of how to accomplish this?

TLDR: Trees of "revocable" / "suspendible" credentials, anyone building them / want to see guidance on them added to this spec or the core data model.

**Comment by decentralgabe** [comment]
IMO this raises a broader point about validating sets of credentials, or dependent credentials - that work isn't handled/defined anywhere that I'm aware of. I was chatting with Paul from GS1 about a similar problem they are facing (not sure of his GitHub).

Perhaps worth a new CCG item or similar.

**Comment by paulfdietrich** [comment]
@decentralgabe. GS1 does have this issue but I am not sure how status is related.

**Comment by KDean-GS1** [comment]
I don't know that this can be developed in a generic fashion. This gets into the business logic validation of the credential, not the semantic validation of the credential itself.

**Comment by msporny** [comment]
What is the proposed normative mechanism to achieve this? This feels like non-normative guidance, implementation guidance, or similar. Don't know what we could add to the spec, other than non-normative guidance.

**Comment by Sakurann** [comment]
TPAC VC WG. use-case is valid. consensus that no normative additional mechanism is needed in the specification - unless any normative requirements come up within a week, closing this issue. 

Having said that, WG is ok adding a non-normative/implementation considerations kind of sentence on this topic if there is an appetite PR is needed, let's relabel this one or open a new issue

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-15-vcwg#section1-2) on 2023-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. Cascading status updates (issue vc-status-list-2021#84)

_See github issue [vc-status-list-2021#84](https://github.com/w3c/vc-status-list-2021/issues/84)._




**Brent Zundel:** suspension of a root credential should cause a child credential to fail .... does anyone have this problem too?  
… the relationship status ... question about statuses of multiple credentials ... combinatorial status ...  
… need to get recommendations or just chat?  

**Kevin Dean:** ... if my credential is revoked ... it may have an impact on credentials that i have issued ...  
… ... any credentials i issued up to that point ... in rare circumstances it may affect credentials i issued in the past ...  

**Gabe Cohen:** that seems like a legitimate need ...  
… seems like a protocol-level decision ...  
… another spec another place may be better.  

**Brent Zundel:** +1, agree that this is a problem, not sure that status list 2021 is the right place to do that specification.  

> *Kristina Yasuda:* +1, agree this is about how the issuer manages multiple credential statuses.

**Brent Zundel:** not even sure if it is within the scope of the charter that it is ...  
… we are short on time ,..  

> *Gabe Cohen:* more broadly dependent/complex validation logic is ill-defined.

**Manu Sporny:** yes, i'd echo what gabe and brent and kristina had said on irc ...  
… maybe this is language that could go in the VC data model ... i don't think this is something that the status list spec should talk about ,....  
… even if it does, it would have to be non-normative ...  

> *Paul Dietrich:* What is relevant to status spec is that the multi-bit options for status could affect business logic during validation.

**Brent Zundel:** recommending that it remains open?  
… or close?  

**Manu Sporny:** orie?  
… not pre-cr, post-cr ... my suggestion is seeing if orie objects to closing it ...  

**Kristina Yasuda:** we heard that there are use cases for that ...  

**Joe Andrieu:** i have the same question ... what's the proposed mechanisms? i think this really goes in implementation guide ...  

> *Kevin Dean:* +1 to Joe.

**Ted Thibodeau Jr.:** VC allows me to know that "Joe said something".  

**ted:** some metadata, dates, etc, but the full infrastructure that's required for whether something is revoked is not built into this, do not recommend it.  

> *Dmitri Zagidulin:* `@TallTed` - not sure I fully understand? credentialStatus is an integral part of VCs..

**Brent Zundel:** labelling it to "pending close", orie can comment and we can go from there.  
… unclear what normative changes would be required.  
… next, talking about 82.  

> *Ted Thibodeau Jr.:* dmitriz — What happens if your credentialStatus lookup fails? once? 3 times over 7 days? This is business logic.

</details>

**Comment by brianorwhatever** [comment]
This seems like something the [confidence method](https://github.com/w3c-ccg/confidence-method-spec) extension point could handle well

**Comment by OR13** [comment]
I suggest an informative example be added, with JSON that developers can blindly copy paste to achieve interoperability in mechanism execution.

I don't think confidenceMethod should be used.

**Comment by OR13** [comment]
I'd like to keep this open.

**Comment by OR13** [comment]
Its not pre-cr, but I have self assigned, I am also OK closing it in the future, once people realize they don't need this.

**Comment by msporny** [comment]
Noting that @OR13 has stepped down as Editor for this specification, it's unlikely that this issue will see forward progress. I'm marking it as pending 7 day close. Someone else will have to step up w/ a concrete proposal in order to keep this issue alive.

**Comment by KDean-GS1** [comment]
Per my [previous comment](https://github.com/w3c/vc-bitstring-status-list/issues/84#issuecomment-1720863562), I don't think this can be developed in a generic fashion and there cannot therefore be a normative specification for handling it. A couple of examples:

### GS1 Identification Licensing

A GS1 user company has an annually-renewable license for a GS1 Company Prefix (the first few digits of any GS1 identification key the company issues to identify its products, locations, and other supply chain artefacts). It doesn't pay the renewal fee. According to the policy of GS1 Utopia, the GS1 Member Organization that issued the license, the company has a grace period of 90 days, after which their license is suspended; if they don't pay within another 90 days, their license is revoked, otherwise the suspension status is cleared.

During the suspension period, a trading partner seeking to verify some information about one of the company's products is presented with the necessary credentials. During the validation process, they seek to validate the Global Trade Item Number (GTIN) allocated to the product, and discover that the underlying GS1 Company Prefix license has been suspended. The trading partner rejects the presentation because of this, so the company goes back to GS1 Utopia to pay the outstanding invoice, and GS1 Utopia removes the "suspended" status. The trading partner goes through the verification process again and accepts the presentation.

Note that it doesn't matter _when_ the presented credentials themselves were issued (before or during the license suspension); the GS1 validation rules require only that the license be active at the time of validation, and it doesn't distinguish between those issued before the license suspension and those issued during it, and those issued during it are valid once the suspension is lifted. In fact, except for situations where someone is maintaining historical copies of downloaded status bit lists, there is no permanent record of the suspension.

### Physician Licensing

A physician is licensed to practice by its local professional association, which provides a credential stating the scope of practice and any other relevant information. A patient traveling to Utopia is required to be vaccinated against diseases its government considers to be a risk and to provide proof of vaccination as part of their visa application. The patient visits the physician, who administers the necessary vaccinations and issues the appropriate credential.

Shortly after the vaccination credential is issued, and before the patient has a chance to present the vaccination credential, the physician's license is suspended. Now it gets tricky, because the professional association doesn't reveal anything about the suspension except the fact of the suspension itself and, perhaps, the date/time the suspension is effective.

In the best case scenario, the local visa office determines (through an integrated or out-of-band process) that the suspension was applied after the vaccine was administered, and so accepts the presentation and issues the visa. Alternately, the local visa office determines that the reason for the suspension is related to the vaccination (e.g., the physician is under investigation for falsifying vaccination records), and so rejects the presentation and refuses the visa.

How exactly either of these is determined is an open question. Perhaps the medical community got together and defined a specification for retrieving the effective date/time of a status, or the status file includes the effective date/time in the status index, with a null or zero value representing that the status doesn't apply. Or perhaps the community standardized an API that, when queried with a dependent credential issued by the physician, returns a definitive "yes" or "no" as to the validity of the credential without revealing any other information (e.g., it could respond "yes" if the physician is under investigation for inappropriate but unrelated personal behaviour or "no" if for falsifying vaccination records). Alternately, there is no date/time in the status file and no standardized API, and anyone presented with a dependent credential is required to call the professional association that issued the license and validate the presentation out of band.

An important distinction with this use case is that any credentials issued by the physician during the suspension period, even if the physician is ultimately reinstated, are **by definition** invalid, because the suspension forbids them from practicing at all. This requires there to be an effective date/time of the suspension, as well as an effective date/time of reinstatement, so that any credentials issued by the physician between them are rejected.

---

This gets to a broader question of the definition of "status". The GS1 use case doesn't care about the effective date/time or the reason for a suspension or revocation, only that the status is there when validation is taking place. The physician use case very much cares; a physician whose license to practice was revoked because they moved to another jurisdiction should have little difficulty getting a new license in the new jurisdiction, whereas one whose license was revoked for violation of professional standards should find it very difficult, if not impossible, to be licensed elsewhere. "When" and "why" are irrelevant for the GS1 use case and critically important for the physician use case, and the "why" for the physician may be available only on a need-to-know basis for privacy protection. There is no normative way to approach this.
