### ISSUE TITLE
Bounds checking

### ISSUE THREAD

**Issue by clehner** [w3c/vc-bitstring-status-list#9]
If the credential status index is out of bounds for the list (i.e. it is a negative number, or greater than the size of the list), should that be considered equivalent to if de-referenced to a `0`, or to a `1`; or should it raise an error?

**Comment by msporny** [comment]
it should raise an error.

**Comment by mprorock** [comment]
non normative 406 might be a sane path as well as normative on throw an error

**Comment by dlongley** [comment]
> non normative 406 might be a sane path as well as normative on throw an error

The index isn't sent to the server that provides the status list VC, so this would be a client-side / verifier error, I'd think. If you're referring to something like a verifier service provided by the VC API ... I'd expect the appropriate behavior to be defined in that spec.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-31-vcwg-special#section2-4) on 2023-01-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.4. Bounds checking (issue vc-status-list-2021#9)

_See github issue [vc-status-list-2021#9](https://github.com/w3c/vc-status-list-2021/issues/9)._




**Brent Zundel:** if the index is out of bounds... what should happen.  

**Manu Sporny:** it should raise an error.  
… if they are out of bounds, it should raise an error..  

> *Michael Prorock:* ill volunteer for a PR on this.

**Kristina Yasuda:** I don't disagree... throwing an error is fine, but perhaps we should define an error code?.  
… are there error codes?.  

**Manu Sporny:** checking the status index is part of the verification stage.  
… that would cause verify to fail.  
… it gets into protocol.  

> *Kristina Yasuda:* error message?.

**Manu Sporny:** all we can say is you should throw an error.  
… we don't have error codes yet.  
… there is no way to surface these to the caller, unless we talk about protocol like vc api.  
… i don't think this spec, which is just data model and serialization, can say much about how errors are exposed.  

**Michael Prorock:** i'm not opposed to including informative guidance.  
… like 406 / not acceptable.  
… normative path, we should say MUST throw an error.  

> *Phil ASU:* +1 to it should throw an error.

**Michael Prorock:** should users see it? we can't say anything about that.  

> *Michael Prorock:* +1 manu.

**Manu Sporny:** is there confusion over getting the list, like 404... vs during verification 406 might not make sense... maybe better 200 verified false.  
… seems like a protocol trap.  

> *Michael Prorock:* agreed.

**Kristina Yasuda:** good point on retrieval vs verify in the bitmap.  
… we should say 404 if its obvious is should be 404.  

> *Manu Sporny:* +1 kristina, not finding the status list should be a 404 and should be in the spec..

**Kristina Yasuda:** if we want to avoid protocol, error message is probably also a trap.  

**Manu Sporny:** we can define an algorithmic error message.  
… error_index_out_of_bounds and hand wave about it.  
… languages / implementers can define how they want to handle it.  

> *Michael Prorock:* +1 manu, e.g. you MUST return an error that indicates that the index is out of range through ERR_ABOVE_MAX.

</details>

**Comment by msporny** [comment]
PR #104 has been raised to address this issue. This issue will be closed once PR #104 has been merged.

**Comment by msporny** [comment]
PR #104 has been merged, closing.
